"""empty message

Revision ID: e09ca5f209cc
Revises: 
Create Date: 2021-05-27 12:38:17.197674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09ca5f209cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('level_0', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('verified', sa.Integer(), nullable=False),
    sa.Column('reviewTime', sa.String(length=120), nullable=True),
    sa.Column('reviewerID', sa.String(length=120), nullable=True),
    sa.Column('productID', sa.String(length=120), nullable=False),
    sa.Column('reviewerName', sa.String(length=120), nullable=True),
    sa.Column('reviewText', sa.String(length=120), nullable=True),
    sa.Column('summary', sa.String(length=120), nullable=False),
    sa.Column('unixReviewText', sa.Integer(), nullable=True),
    sa.Column('vote', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('level_0', 'verified', 'productID', 'summary')
    )
    op.create_index(op.f('ix_reviews_index'), 'reviews', ['index'], unique=True)
    op.create_index(op.f('ix_reviews_overall'), 'reviews', ['overall'], unique=True)
    op.create_index(op.f('ix_reviews_reviewText'), 'reviews', ['reviewText'], unique=True)
    op.create_index(op.f('ix_reviews_reviewTime'), 'reviews', ['reviewTime'], unique=True)
    op.create_index(op.f('ix_reviews_reviewerID'), 'reviews', ['reviewerID'], unique=True)
    op.create_index(op.f('ix_reviews_reviewerName'), 'reviews', ['reviewerName'], unique=True)
    op.create_index(op.f('ix_reviews_unixReviewText'), 'reviews', ['unixReviewText'], unique=True)
    op.create_index(op.f('ix_reviews_vote'), 'reviews', ['vote'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_vote'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_unixReviewText'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewerName'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewerID'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewTime'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewText'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_overall'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_index'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
